@baseUrl = http://127.0.0.1:8000

##Categoria

### creamos una categoria
POST {{baseUrl}}/categorias/
Content-Type: application/json

{
  "nombre" : "pizzas",
  "descripcion" : "Deliciosas pizzas artesanales con ingredientes frescos y sabores auténticos, perfectas para compartir en cualquier ocasión."
}

### listamos las categorias
GET {{baseUrl}}/categorias/

### eliminar categoria
DELETE {{baseUrl}}/categorias/9

###Producto

POST {{baseUrl}}/productos/
Content-Type: application/json

{
  "nombre" : "Pizza Napolitana",
  "descripcion" : " La Pizza Napolitana es una deliciosa creación culinaria que se caracteriza por su masa delgada y crujiente, cubierta con una generosa capa de salsa de tomate fresca, queso mozzarella derretido y rodajas de tomate. Esta pizza tradicional italiana se hornea a alta temperatura, lo que le confiere un sabor auténtico y una textura irresistible. Es una opción perfecta para los amantes de la pizza que buscan una experiencia gastronómica clásica y llena de sabor.",
  "precio_base": 1500.00,
  "stock_cantidad": 10
}

### update producto
PATCH   {{baseUrl}}/productos/1
Content-Type: application/json

{
  "stock_cantidad": 8
}

### listar productos
GET {{baseUrl}}/productos/


### eliminar producto
DELETE {{baseUrl}}/productos/3


###ingrediente

### crear ingrediente
POST {{baseUrl}}/ingredientes/
Content-Type: application/json

{
  "nombre" : "sal",
  "descripcion" : "Sal marina de alta calidad, utilizada para realzar el sabor de platos y conservar los alimentos."
}
### actualizar ingrediente
PATCH {{baseUrl}}/ingredientes/1
Content-Type: application/json

{
  "es_alergeno": true
}
### listar ingredientes
GET {{baseUrl}}/ingredientes/


### crear relacion producto-categoria
POST {{baseUrl}}/productos/categorias
Content-Type: application/json

{
  "producto_id": 5,
  "categoria_id": 10,
  "es_principal": true
}


### crear relacion producto-ingrediente
POST {{baseUrl}}/productos/ingredientes
Content-Type: application/json

{
  "producto_id": 5,
  "ingrediente_id": 5,
  "es_removible": false
}



###Usuario
### crear usuario
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
  "nombre": "Andres",
  "apellido": "Mamani",
  "email": "andres@gmail.com",
  "celular": "2615551543",
  "password": "654321"
}
### Listar usuarios
GET {{baseUrl}}/usuarios
### Listar usuario por id
GET {{baseUrl}}/usuarios/1
### actualizar usuario
PATCH {{baseUrl}}/usuarios/1
Content-Type: application/json

{
  "nombre": "Hernan Actualizado"
}
### eliminar usuario
DELETE {{baseUrl}}/usuarios/1

###Usuario-rol
### asignar rol a usuario
POST {{baseUrl}}/usuarios/roles
Content-Type: application/json

{
  "usuario_id": 4,
  "rol_codigo": "ADMIN",
  "asignado_por_id": 1
}

### listar roles de usuario
GET {{baseUrl}}/usuarios/4/roles

### quitar rol de usuario
DELETE {{baseUrl}}/usuarios/1/roles/ADMIN